### PR TITLE
spi: enable slave mode

### PR DESCRIPTION
**Pull request by LiZhengke**
the SS pin works as a standard ‘chip select’ input and the slave
is selected while the SS line is at its active level.

### CODE REVIEW

**Comment by LiZhengke** [comment]
Is anyone can review my patch please? Thanks.

**Comment by BernardPuel** [comment]
Hello,
Thank you very much for your contribution. SPI Slave mode in Linux is under ST roadmap for a long time but due to low traction from the customer and limited support on Linux framework, it was never developed.
Your contribution was done on 4.19 branch that is no longer maintained by ST (so ST will not deliver again on this stream), so 
ST will never merge it in this branch. But I guess these patches can be helpful for other customers/developers.

Current supported branches are 5.4 (V2 ecosystem) and 5.10 (V3 ecosystem). As soon as the V4 (so 5.15 kernel) will be delivered V2 will stop to be maintained by ST (but can be maintained by customers thanks to ST partners help).

By the way, you contribution is also interesting for ST roadmap and could speed up the support of SPI Slave feature within next ST deliveries. This will need a complete analysis on ST side and we will come back with the outcomes soon.

**Comment by BernardPuel** [comment]
SPI Slave feature was delivered in V4.1.0 Delivery: https://wiki.st.com/stm32mpu/wiki/STM32_MPU_ecosystem_release_note_-_v4.1.0.

Thanks again for your contribution.

**Comment by BernardPuel** [comment]
then close the PR.

**Pull request closed without merging**
