### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by YafengGao777**
fix compatible="panel-dpi" node not have data-mapping will cause panic.

### CODE REVIEW

**Comment by SeraphCD** [comment]
In my project, an exception will be triggered in the _databtsvc

**Comment by YafengGao777** [comment]
Isn't this a bug, or is it because it won't affect

**Comment by BernardPuel** [comment]
Thanks for your contribution. For me this is a bug and I have entered an internal ticket for that.
I will keep you aware of the follow up ...

**Comment by ST-dot-com** [comment]
This pull request has been refused, the <a href='https://cla.st.com'>Contribution License Agreement</a> must be signed.

**Comment by YafengGao777** [comment]
What has happened

**Comment by BernardPuel** [comment]
Your patch was integrated in latest release (V5.1.0 ecosystem release).
Thanks again !

**Pull request closed without merging**
