### PR TITLE
Abuzarra/fix resume eth mac

### PR DESCRIPTION
**Pull request by abuzarra**

### CODE REVIEW

**Comment by abuzarra** [comment]
This PR is related with the support case #00176836

**Comment by BernardPuel** [comment]
Thanks for your contribution. Correction will be part of V5.0 release and probably also next V4 maintenance release (under validation).

**Comment by BernardPuel** [comment]
It will be also part of V4.1.1 (that will arrive a bit after V5 June delivery).

**Comment by Sandahsoni** [comment]
Hii

**Comment by BernardPuel** [comment]
Hi

**Comment by BernardPuel** [comment]
the patch was delivered in V5.0.0 and will be also delivered in V4.1.1 next week.

**Pull request closed without merging**
